export const GET_CATEGORIES_SUCCESS = 'products/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'products/GET_CATEGORIES_FAILURE';
export const GET_PRODUCTS_SUCCESS = 'products/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'products/GET_PRODUCTS_FAILURE';
